on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

permissions: {}

jobs:
  slsa-attestation:
    permissions:
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download release artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release download ${{ github.event.inputs.tag }} --dir /tmp/release-artifacts
      - name: Generate SLSA attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: |
            /tmp/release-artifacts/*.tar.gz
            /tmp/release-artifacts/*.zip
